language: swift
osx_image: xcode10.1

before_install:
    - pod --version
    
script:
    - pod lib lint
    - xcodebuild test -project Duration.xcodeproj -scheme DurationTests -destination 'platform=iOS Simulator,name=iPhone SE' | xcpretty
