language: swift
osx_image: xcode12.2

before_install:
  - rvm use $RVM_RUBY_VERSION
  - bundle config --local build.nokogiri --use-system-libraries

install: 
  - bundle install --without=documentation --path ../travis_bundle_dir 

script:
    - pod lib lint
    - xcodebuild test -project Duration.xcodeproj -scheme DurationTests -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
    - bundle exec slather coverage -s --ignore DurationTests/\* --scheme Duration Duration.xcodeproj

after_success: 
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode
